import React, { useContext } from "react";
import { Context } from "./../ContextProvider";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Bar } from "react-chartjs-2";
import { Link } from "@mui/material";
// import theme from "./styles/Styles";
//import faker from 'faker';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

export const options = {
  indexAxis: "y" as const,
  elements: {
    bar: {
      borderWidth: 2,
    },
  },
  responsive: true,
  plugins: {
    legend: {
      position: "bottom" as const,
    },
    title: {
      display: true,
      // text: "My carbon footprint",
    },
  },
};

export const BarChart = () => {
  const { emission } = useContext(Context);
  const labels = [""];
  const data = {
    labels,
    datasets: [
      {
        label: "My emission [t]",
        //data: labels.map(() => faker.datatype.number({ min: 0, max: 1000 })),
        data: [emission / 1000],
        backgroundColor: "#af4448",
      },
      {
        label:
          "This is the average annual amount of CO₂ generated by a single person in the EU [8.4 t]",
        //data: labels.map(() => faker.datatype.number({ min: 0, max: 1000 })),
        data: [8.4],
        backgroundColor: "#e57373",
      },
      {
        label:
          "Maximum amount of CO₂ that can be generated by a single person in a year to stop climate change [0.6 t]",
        //data: labels.map(() => faker.datatype.number({ min: 0, max: 1000 })),
        data: [0.6],
        backgroundColor: "#46a38c",
        //"#00695c",
      },
    ],
  };

  return (
    <>
      {/* <ThemeProvider theme={theme}> */}
      <div style={{ width: "650px", margin: "auto auto" }}>
        <Bar options={options} data={data} />
        <Link
          href="https://co2.myclimate.org/en/portfolios?calculation_id=5239733"
          target="blank"
          color="inherit"
          fontSize={10}
        >
          * Source ofdata
        </Link>
      </div>
      {/* </ThemeProvider> */}
    </>
  );
};
