import React, { useContext } from "react";
import { Context } from "./../ContextProvider";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Bar } from "react-chartjs-2";
import { Link } from "@mui/material";

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

export const options = {
  responsive: true,
  plugins: {
    legend: {
      position: "bottom" as const,
    },
    title: {
      display: true,
    },
  },
};

export const VertBarChart = () => {
  const { totalEmission } = useContext(Context);
  const labels = [""];
  const data = {
    labels,
    datasets: [
      {
        label: "My total emission [t]",
        data: [+totalEmission / 1000],
        backgroundColor: "#af4448",
      },

      {
        label:
          "Maximum amount of CO₂ that can be generated by a single person in a year to stop climate change [0.6 t]",
        data: [0.6],
        backgroundColor: "#46a38c",
      },

      {
        label:
          "This is the average annual amount of CO₂ generated by a single person in the EU [8.4 t]",
        data: [8.4],
        backgroundColor: "#e57373",
      },
    ],
  };

  return (
    <>
      <div style={{ width: "50vw", margin: "auto auto", marginBottom: "2em" }}>
        <Bar options={options} data={data} />
        <Link
          href="https://www.myclimate.org/"
          target="blank"
          color="#babdbe"
          fontSize={10}
          underline="hover"
        >
          * Source of data
        </Link>
      </div>
    </>
  );
};
