import i18next from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

i18next
  .use(initReactI18next)
  .use(LanguageDetector)
  .init({
    fallbackLng: "en",
    resources: {
      en: {
        translation: {
          // NAVIGATION
          home: "Home",
          profile: "Profile",
          signOut: "Sign Out",
          signIn: "Sign In",
          // LANDING PAGE
          reaching:
            "Reaching 100% CO₂ emission reduction target for both new cars and vans by 2035 is possible.",
          theCouncil:
            "The Council and the European Parliament reached a provisional agreement on stricter CO₂ emission performance standards for new cars and vans. Pending a formal adoption, the co-legislators agreed to a 55% CO₂ emission reduction target for new cars and 50% for new vans by 2030 compared to 2021 levels and to a 100% CO₂ emission reduction target for both new cars and vans by 2035.",
          learnMore: "Learn more",
          useCO2:
            "Use CO₂CAR to check the emission levels for your current or next car!",
          // LOGIN & REGISTER
          errorAllFields: "All fields are required",
          errorInvalidEmail: "Invalid email address",
          errorNoAccount: "Email not yet registered",
          errorAlreadyExists: "An account with this email already exists",
          errorIncorrectPassword: "Incorrect password",
          errorPasswordsDifferent: "Entered passwords are different",
          errorWeakPassword:
            "Your password need to contain at least 6 characters",
          emailLabel: "E-mail",
          emailPlaceholder: "enter e-mail",
          passwordLabel: "Password",
          passwordPlaceholder: "enter password",
          password2Label: "Repeated password",
          password2Placeholder: "repeat password",
          signInAnd: "Sign in and check your car's emissions!",
          signUpAnd: "Sign up and check your car's emissions!",
          signUp: "Sign up",
          dontHave: "Don't have an account yet?",
          alreadyHave: "Already have an account?",
          goToRegister: "Go to registration instead.",
          goToLogin: "Go to login instead.",
          continue: "Continue without signing in",
          // HOME
          calculateYour: "Calculate your car's carbon emission",
          distanceLabel: "Distance (km)",
          makeLabel: "Make",
          modelLabel: "Model",
          calculateButton: "Calculate emission",
          resultUnit: "kg of CO₂",
          save: "Save result",
          tooltip: "Sign in to use this feature",
          // PROFILE
          myData: "My Data",
          annualAmount: "The amount of your car's annual carbon emission is",
          delete: "Delete",
          listEntry: "",
          // CHARTS
          chartLabelMine: "My emission",
          chartLabelEUMonth: "This is the average monthly amount of CO₂ generated by a single person in the EU",
          chartLabelAcceptable: "Maximum amount of CO₂ that can be generated by a single person in a year to stop climate change",
          chartLabelEUYear: "This is the average annual amount of CO₂ generated by a single person in the EU",
          source: "Source of data",
        },
      },
      pl: {
        translation: {
          // NAVIGATION
          home: "Strona główna",
          profile: "Profil",
          signOut: "Wyloguj",
          signIn: "Zaloguj",
          // LANDING PAGE
          reaching:
            "Reaching 100% CO₂ emission reduction target for both new cars and vans by 2035 is possible.",
          theCouncil:
            "The Council and the European Parliament reached a provisional agreement on stricter CO₂ emission performance standards for new cars and vans. Pending a formal adoption, the co-legislators agreed to a 55% CO₂ emission reduction target for new cars and 50% for new vans by 2030 compared to 2021 levels and to a 100% CO₂ emission reduction target for both new cars and vans by 2035.",
          learnMore: "Dowiedz się więcej",
          useCO2:
            "Use CO₂CAR to check the emission levels for your current or next car!",
          // LOGIN & REGISTER
          errorAllFields: "Wszystkie pola są wymagane",
          errorInvalidEmail: "Niepoprawny adres email",
          errorNoAccount: "Konto na podany adres nie istnieje",
          errorAlreadyExists: "Konto na podany adres już istnieje",
          errorIncorrectPassword: "Niepoprawne hasło",
          errorPasswordsDifferent: "Podane hasła nie są takie same",
          errorWeakPassword:
            "Hasło musi zawierać przynajmniej 6 znaków",
          emailLabel: "E-mail",
          emailPlaceholder: "podaj e-mail",
          passwordLabel: "Hasło",
          passwordPlaceholder: "podaj hasło",
          password2Label: "Powtórzone hasło",
          password2Placeholder: "powtórz hasło",
          signInAnd: "Zaloguj się i sprawdź poziom emisji swojego samochodu!",
          signUpAnd: "Zarejestruj się i sprawdź poziom emisji swojego samochodu!",
          signUp: "Zarejestruj",
          dontHave: "Nie masz jeszcze konta?",
          alreadyHave: "Masz już konto?",
          goToRegister: "Przejdź do rejestracji.",
          goToLogin: "Przejdź do logowania.",
          continue: "Kontynuuj bez logowania",
          // HOME
          calculateYour: "Calculate your car's carbon emission",
          distanceLabel: "Distance (km)",
          makeLabel: "Make",
          modelLabel: "Model",
          calculateButton: "Calculate emission",
          resultUnit: "kg of CO₂",
          save: "Save result",
          tooltip: "Sign in to use this feature",
          // PROFILE
          myData: "My Data",
          annualAmount: "The amount of your car's annual carbon emission is",
          delete: "Delete",
          listEntry: "",
          // CHARTS
          chartLabelMine: "My emission",
          chartLabelEUMonth: "This is the average monthly amount of CO₂ generated by a single person in the EU",
          chartLabelAcceptable: "Maximum amount of CO₂ that can be generated by a single person in a year to stop climate change",
          chartLabelEUYear: "This is the average annual amount of CO₂ generated by a single person in the EU",
          source: "Source of data",
        },
      },
    },
  });
